# Generated by Django 6.0.2 on 2026-02-25 12:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLogSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("log_date", models.DateField()),
                ("day_number_in_trip", models.IntegerField()),
                (
                    "total_driving_hours_day",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "total_on_duty_nd_hours_day",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "total_sleeper_hours_day",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "total_off_duty_hours_day",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "cumulative_hos_start",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "cumulative_hos_end",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "start_day_odometer",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "end_day_odometer",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "from_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "to_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "carrier_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "driver_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "vehicle_numbers",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "shipping_doc_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
            ],
            options={
                "db_table": "daily_log_sheets",
                "ordering": ["trip", "day_number_in_trip"],
            },
        ),
        migrations.CreateModel(
            name="GeocodeCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_input", models.CharField(db_index=True, max_length=500)),
                ("resolved_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("resolved_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "canonical_address",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "provider",
                    models.CharField(default="openrouteservice", max_length=30),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "geocode_cache",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("dot_number", models.CharField(blank=True, default="", max_length=20)),
                ("mc_number", models.CharField(blank=True, default="", max_length=20)),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("address", models.CharField(blank=True, default="", max_length=500)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("invitation_expiry_days", models.IntegerField(default=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("initial_pickup", "Initial Pickup"),
                            ("final_dropoff", "Final Dropoff"),
                            ("fuel", "Fuel Stop"),
                            ("rest_30min", "30-Minute Break"),
                            ("rest_10hr", "10-Hour Rest"),
                            ("sleeper", "Sleeper Berth"),
                            ("waypoint", "Waypoint"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sequence_number", models.IntegerField()),
                ("location_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("location_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "address_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("scheduled_arrival_time", models.DateTimeField(blank=True, null=True)),
                (
                    "scheduled_departure_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("duration_minutes", models.IntegerField(default=0)),
                (
                    "odometer_at_stop",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "distance_from_prev_stop",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_hos_mandated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "stops",
                "ordering": ["trip", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("platform_admin", "Platform Admin"),
                            ("org_admin", "Org Admin"),
                            ("dispatcher", "Dispatcher"),
                            ("driver", "Driver"),
                            ("fleet_manager", "Fleet Manager"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "personal_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("resend_count", models.IntegerField(default=0)),
                ("last_resent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="trip_planner.organization",
                    ),
                ),
            ],
            options={
                "db_table": "invitations",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("invitation_sent", "Invitation Sent"),
                            ("invitation_accepted", "Invitation Accepted"),
                            ("invitation_revoked", "Invitation Revoked"),
                            ("member_deactivated", "Member Deactivated"),
                            ("vehicle_assigned", "Vehicle Assigned"),
                            ("vehicle_unassigned", "Vehicle Unassigned"),
                            ("trip_assigned", "Trip Assigned"),
                            ("trip_created", "Trip Created"),
                            ("org_created", "Organization Created"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="trip_planner.organization",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("platform_admin", "Platform Admin"),
                            ("org_admin", "Org Admin"),
                            ("dispatcher", "Dispatcher"),
                            ("driver", "Driver"),
                            ("fleet_manager", "Fleet Manager"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deactivated_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="trip_planner.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organization_members",
                "unique_together": {("organization", "user")},
            },
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "license_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "license_state",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                (
                    "home_terminal_address",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "co_driver_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "current_cycle_used_hours",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("cycle_reset_at", models.DateTimeField(blank=True, null=True)),
                ("profile_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org_member",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_profile",
                        to="trip_planner.organizationmember",
                    ),
                ),
            ],
            options={
                "db_table": "driver_profiles",
            },
        ),
        migrations.CreateModel(
            name="DutyStatusSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("driving", "Driving"),
                            ("on_duty_nd", "On Duty (Not Driving)"),
                            ("sleeper_berth", "Sleeper Berth"),
                            ("off_duty", "Off Duty"),
                        ],
                        max_length=15,
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=0)),
                (
                    "start_location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "start_location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "end_location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "end_location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "distance_traveled_miles",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "segment_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sequence_in_day", models.IntegerField(default=0)),
                (
                    "daily_log_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="trip_planner.dailylogsheet",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segments",
                        to="trip_planner.stop",
                    ),
                ),
            ],
            options={
                "db_table": "duty_status_segments",
                "ordering": ["daily_log_sheet", "sequence_in_day"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "input_current_lat",
                    models.DecimalField(decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "input_current_lng",
                    models.DecimalField(decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "input_pickup_lat",
                    models.DecimalField(decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "input_pickup_lng",
                    models.DecimalField(decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "input_dropoff_lat",
                    models.DecimalField(decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "input_dropoff_lng",
                    models.DecimalField(decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "input_current_address",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "input_pickup_address",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "input_dropoff_address",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "input_cycle_used_hours",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "remaining_cycle_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "total_trip_distance_miles",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=8, null=True
                    ),
                ),
                (
                    "total_trip_duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "total_driving_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("calculated_trip_days", models.IntegerField(blank=True, null=True)),
                ("route_polyline_json", models.TextField(blank=True, default="")),
                ("cycle_exhausted_mid_trip", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("assigned", "Assigned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("planned_start_datetime", models.DateTimeField(blank=True, null=True)),
                ("planned_end_datetime", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="trip_planner.organization",
                    ),
                ),
            ],
            options={
                "db_table": "trips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stop",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                to="trip_planner.trip",
            ),
        ),
        migrations.CreateModel(
            name="HOSViolation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("cycle_limit_exceeded", "70-Hour Cycle Limit Exceeded"),
                            ("driving_over_11hr", "Driving Over 11 Hours"),
                            ("window_over_14hr", "On-Duty Window Over 14 Hours"),
                            ("missing_30min_break", "Missing 30-Minute Break"),
                        ],
                        max_length=30,
                    ),
                ),
                ("violation_time", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("critical", "Critical")],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "daily_log_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="violations",
                        to="trip_planner.dailylogsheet",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="trip_planner.trip",
                    ),
                ),
            ],
            options={
                "db_table": "hos_violations",
            },
        ),
        migrations.AddField(
            model_name="dailylogsheet",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_logs",
                to="trip_planner.trip",
            ),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("truck_number", models.CharField(max_length=50)),
                (
                    "trailer_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "license_plate",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("vin", models.CharField(blank=True, default="", max_length=17)),
                (
                    "odometer_current",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_driver_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vehicle",
                        to="trip_planner.driverprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="trip_planner.organization",
                    ),
                ),
            ],
            options={
                "db_table": "vehicles",
                "unique_together": {("organization", "truck_number")},
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="trip_planner.vehicle",
            ),
        ),
    ]
