# Generated by Django 6.0.2 on 2026-02-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip_planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("INVITATION_SENT", "Invitation Sent"),
                    ("INVITATION_ACCEPTED", "Invitation Accepted"),
                    ("INVITATION_REVOKED", "Invitation Revoked"),
                    ("MEMBER_DEACTIVATED", "Member Deactivated"),
                    ("VEHICLE_ASSIGNED", "Vehicle Assigned"),
                    ("VEHICLE_UNASSIGNED", "Vehicle Unassigned"),
                    ("TRIP_ASSIGNED", "Trip Assigned"),
                    ("TRIP_CREATED", "Trip Created"),
                    ("ORG_CREATED", "Organization Created"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="dutystatussegment",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRIVING", "Driving"),
                    ("ON_DUTY_ND", "On Duty (Not Driving)"),
                    ("SLEEPER_BERTH", "Sleeper Berth"),
                    ("OFF_DUTY", "Off Duty"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="hosviolation",
            name="severity",
            field=models.CharField(
                choices=[("WARNING", "Warning"), ("CRITICAL", "Critical")],
                default="WARNING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="hosviolation",
            name="violation_type",
            field=models.CharField(
                choices=[
                    ("CYCLE_LIMIT_EXCEEDED", "70-Hour Cycle Limit Exceeded"),
                    ("DRIVING_OVER_11HR", "Driving Over 11 Hours"),
                    ("WINDOW_OVER_14HR", "On-Duty Window Over 14 Hours"),
                    ("MISSING_30MIN_BREAK", "Missing 30-Minute Break"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("PLATFORM_ADMIN", "Platform Admin"),
                    ("ORG_ADMIN", "Org Admin"),
                    ("DISPATCHER", "Dispatcher"),
                    ("DRIVER", "Driver"),
                    ("FLEET_MANAGER", "Fleet Manager"),
                    ("VIEWER", "Viewer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("EXPIRED", "Expired"),
                    ("REVOKED", "Revoked"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("PLATFORM_ADMIN", "Platform Admin"),
                    ("ORG_ADMIN", "Org Admin"),
                    ("DISPATCHER", "Dispatcher"),
                    ("DRIVER", "Driver"),
                    ("FLEET_MANAGER", "Fleet Manager"),
                    ("VIEWER", "Viewer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="type",
            field=models.CharField(
                choices=[
                    ("INITIAL_PICKUP", "Initial Pickup"),
                    ("FINAL_DROPOFF", "Final Dropoff"),
                    ("FUEL", "Fuel Stop"),
                    ("REST_30MIN", "30-Minute Break"),
                    ("REST_10HR", "10-Hour Rest"),
                    ("SLEEPER", "Sleeper Berth"),
                    ("WAYPOINT", "Waypoint"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ASSIGNED", "Assigned"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=15,
            ),
        ),
    ]
