# Generated by Django 6.0.2 on 2026-02-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip_planner", "0003_remove_viewer_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("INVITATION_SENT", "Invitation Sent"),
                    ("INVITATION_ACCEPTED", "Invitation Accepted"),
                    ("INVITATION_REVOKED", "Invitation Revoked"),
                    ("MEMBER_DEACTIVATED", "Member Deactivated"),
                    ("VEHICLE_ASSIGNED", "Vehicle Assigned"),
                    ("VEHICLE_UNASSIGNED", "Vehicle Unassigned"),
                    ("TRIP_ASSIGNED", "Trip Assigned"),
                    ("TRIP_CREATED", "Trip Created"),
                    ("ORG_CREATED", "Organization Created"),
                    ("PROFILE_CREATED", "Profile Created"),
                    ("PROFILE_UPDATED", "Profile Updated"),
                ],
                max_length=30,
            ),
        ),
    ]
