apiVersion: v1
kind: ConfigMap
metadata:
  name: spotter-api-config
  namespace: spotter
data:
  DJANGO_SETTINGS_MODULE: "eld_backend.settings.production"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,spotter-api,spotter-api.spotter.svc.cluster.local,*"
  CORS_ALLOWED_ORIGINS: "http://spotter-ui:3000,http://localhost:3000"
  FRONTEND_URL: "http://spotter-ui:3000"
  DB_HOST: "spotter-postgres"
  DB_PORT: "5432"
  DB_NAME: "spotter_k8s"
  DB_USER: "spotter"
  SMTP_HOST: "smtp-relay.brevo.com"
  SMTP_PORT: "587"
