apiVersion: v1
kind: Secret
metadata:
  name: spotter-api-secrets
  namespace: spotter
type: Opaque
stringData:
  # Django core
  SECRET_KEY: "k8s-django-secret-key-change-in-production-xk9m2!"
  INVITATION_JWT_SECRET: "k8s-invite-secret-change-in-production-8f3k!m2"
  # PostgreSQL
  DB_PASSWORD: "spotter_pg_secret"
  # SMTP (Brevo)
  SMTP_USER: "931fc0002@smtp-brevo.com"
  SMTP_PASS: "xsmtpsib-ae968dbfbe313c59947966b7c0974bb025413705aca2a26bed9ee5ca03281dc8-eFmUsCjsjpXRfjbW"
  SMTP_FROM_EMAIL: "dubbalwaryash@gmail.com"
  EMAIL_FROM: "dubbalwaryash@gmail.com"
  # ORS
  ORS_API_KEY: "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjQ4Mzg4ZmFmNTA0MTQzNTI4NTMwYTg2NGExOGZmNjAyIiwiaCI6Im11cm11cjY0In0="
---
apiVersion: v1
kind: Secret
metadata:
  name: spotter-postgres-secret
  namespace: spotter
type: Opaque
stringData:
  POSTGRES_USER: "spotter"
  POSTGRES_PASSWORD: "spotter_pg_secret"
  POSTGRES_DB: "spotter_k8s"
